/* global process, console */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const j = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const write = (p, s) => {
  fs.mkdirSync(path.dirname(path.join(ROOT, p)), { recursive: true });
  fs.writeFileSync(path.join(ROOT, p), s);
};

const mpRoutes = j('artifacts/product-audit/mp-routes.json');
const adminRoutes = j('artifacts/product-audit/admin-routes.json');
const apiEndpoints = j('artifacts/product-audit/api-endpoints.json');
const dbModels = j('artifacts/product-audit/db-models.json');
const controlManifest = j('artifacts/product-audit/control-manifest.json');
const fakeMarkers = j('artifacts/product-audit/fake-markers.json');

// ---------- view -> routes / controls ----------
const viewRoutes = {};
for (const r of mpRoutes.routes) {
  if (!r.component) continue;
  (viewRoutes[r.component] ??= []).push(r.path);
}
const viewControls = {};
for (const c of controlManifest.controls) {
  if (c.surface !== 'mp') continue;
  (viewControls[c.view] ??= []).push(c);
}
const adminViewControls = {};
for (const c of controlManifest.controls) {
  if (c.surface !== 'admin') continue;
  (adminViewControls[c.view] ??= []).push(c);
}

// `api.get<{ item: X }>('/api/v1/tonight')` puts a generic argument list between the
// method and the call parenthesis, so the generic block has to be optional here.
const apiCallRe = /(?:api\.(get|post|patch|put|delete)(?:<[^<>]*(?:<[^<>]*>[^<>]*)*>)?|fetch)\s*\(\s*[`'"]\/api\/([^`'"?]*)/g;
function apiUsage(viewFile, dir) {
  const src = read(path.join(dir, viewFile));
  const reads = new Set();
  const writes = new Set();
  let m;
  const re = new RegExp(apiCallRe.source, 'g');
  while ((m = re.exec(src))) {
    const method = m[1] ? m[1].toUpperCase() : 'GET';
    const target = '/api/' + m[2].replace(/\$\{[^}]*\}/g, ':param');
    if (method === 'GET') reads.add(target);
    else writes.add(`${method} ${target}`);
  }
  return { reads: [...reads].sort(), writes: [...writes].sort() };
}

const mpViews = fs.readdirSync(path.join(ROOT, 'apps/mp/src/views')).filter((f) => f.endsWith('.vue'));
const adminViews = fs.readdirSync(path.join(ROOT, 'apps/admin/src/views')).filter((f) => f.endsWith('.vue'));

// ---------- PRODUCT_INVENTORY.md ----------
const inventory = [];
inventory.push('# PRODUCT INVENTORY');
inventory.push('');
inventory.push(`Generated from the current source tree at HEAD ${process.env.HEAD_SHA ?? 'unknown'}. This file is machine-generated by \`work/generate-reports.mjs\` and must be re-run after any route/view change.`);
inventory.push('');
inventory.push('## Counts');
inventory.push('');
inventory.push('| Metric | Value |');
inventory.push('| --- | ---: |');
inventory.push(`| TOTAL_MP_ROUTES | ${mpRoutes.totalRoutes} |`);
inventory.push(`| TOTAL_MP_UNIQUE_VIEWS | ${mpRoutes.totalUniqueViews} |`);
inventory.push(`| MP_VIEW_FILES | ${mpViews.length} |`);
inventory.push(`| TOTAL_ADMIN_ROUTES | ${adminRoutes.totalRoutes} |`);
inventory.push(`| ADMIN_VIEW_FILES | ${adminViews.length} |`);
inventory.push(`| TOTAL_ADMIN_RESOURCES | ${adminRoutes.menu.length} |`);
inventory.push(`| TOTAL_API_ENDPOINTS | ${apiEndpoints.total} |`);
inventory.push(`| TOTAL_DB_MODELS | ${dbModels.models.length} |`);
inventory.push(`| TOTAL_DB_ENUMS | ${dbModels.enums.length} |`);
inventory.push(`| TOTAL_CONTROLS (static) | ${controlManifest.total} |`);
inventory.push('');
inventory.push('## Tab routes');
inventory.push('');
inventory.push(mpRoutes.tabRoutes.map((r) => `- \`${r}\``).join('\n'));
inventory.push('');
inventory.push('## Alias groups (same component, multiple paths)');
inventory.push('');
inventory.push('| Component | Paths | Count |');
inventory.push('| --- | --- | ---: |');
for (const [comp, paths] of Object.entries(viewRoutes)) {
  if (paths.length > 1) inventory.push(`| ${comp} | ${paths.map((p) => `\`${p}\``).join('<br>')} | ${paths.length} |`);
}
inventory.push('');
inventory.push('## MP routes');
inventory.push('');
inventory.push('| Path | Component | Tab | AliasGroup |');
inventory.push('| --- | --- | --- | ---: |');
for (const r of mpRoutes.routes) {
  inventory.push(`| \`${r.path}\` | ${r.component ?? `(redirect -> ${r.redirect})`} | ${r.tabRoute ? 'yes' : ''} | ${r.aliasCount} |`);
}
inventory.push('');
inventory.push('## Admin routes / resources');
inventory.push('');
inventory.push('| Path | Component | Resource | Group | Title |');
inventory.push('| --- | --- | --- | --- | --- |');
for (const r of adminRoutes.routes) {
  inventory.push(`| \`${r.path}\` | ${r.component ?? `(redirect -> ${r.redirect})`} | ${r.resource ?? ''} | ${r.group ?? ''} | ${r.title ?? ''} |`);
}
inventory.push('');
inventory.push('## DB models');
inventory.push('');
inventory.push(dbModels.models.map((m) => `- ${m.name}`).join('\n'));
inventory.push('');
write('docs/product-audit/PRODUCT_INVENTORY.md', inventory.join('\n'));

// ---------- PAGE_AUDIT_MATRIX.md ----------
const pageMatrix = [];
pageMatrix.push('# PAGE AUDIT MATRIX');
pageMatrix.push('');
pageMatrix.push('One row per unique MP view and per admin resource. `Audit file` links the per-page audit document.');
pageMatrix.push('');
pageMatrix.push('| # | Surface | View | Routes | Controls | API reads | API writes | Audit file | Status |');
pageMatrix.push('| ---: | --- | --- | ---: | ---: | ---: | ---: | --- | --- |');
let i = 0;
for (const v of mpViews) {
  i += 1;
  const name = v.replace(/\.vue$/, '');
  const usage = apiUsage(v, 'apps/mp/src/views');
  const controls = (viewControls[v] ?? []).length;
  const routes = (viewRoutes[name] ?? []).map((p) => `\`${p}\``).join('<br>') || '(none)';
  pageMatrix.push(`| ${i} | mp | ${name} | ${routes} | ${controls} | ${usage.reads.length} | ${usage.writes.length} | [${name}.md](./pages/mp/${name}.md) | PENDING |`);
}
for (const item of adminRoutes.menu) {
  i += 1;
  const comp = adminRoutes.routes.find((r) => r.path === item.path)?.component ?? '(none)';
  pageMatrix.push(`| ${i} | admin | ${item.resource} | \`${item.path}\` | ${(adminViewControls[comp] ?? []).length} | - | - | [${item.resource}.md](./pages/admin/${item.resource}.md) | PENDING |`);
}
pageMatrix.push('');
write('docs/product-audit/PAGE_AUDIT_MATRIX.md', pageMatrix.join('\n'));

// ---------- CONTROL_AUDIT_MATRIX.md ----------
const controlMatrix = [];
controlMatrix.push('# CONTROL AUDIT MATRIX');
controlMatrix.push('');
controlMatrix.push(`Static discovery found ${controlManifest.total} interactive bindings. Status values follow section 129 of the task: REAL / LOCAL_UI_ONLY_BY_DESIGN / BROKEN / FAKE / BLOCKED.`);
controlMatrix.push('');
controlMatrix.push('| # | Surface | View | Kind | Handler | Line | Status |');
controlMatrix.push('| ---: | --- | --- | --- | --- | ---: | --- |');
controlManifest.controls.forEach((c, idx) => {
  const h = String(c.handler).replace(/\|/g, '\\|').replace(/\n/g, ' ').slice(0, 90);
  controlMatrix.push(`| ${idx + 1} | ${c.surface} | ${c.view} | ${c.kind} | \`${h}\` | ${c.line} | PENDING |`);
});
controlMatrix.push('');
write('docs/product-audit/CONTROL_AUDIT_MATRIX.md', controlMatrix.join('\n'));

// ---------- per-page skeletons ----------
const SECTIONS = ['PURPOSE','USER_JOB','ENTRY','EXIT','ROUTES','STATES','CONTROLS','API_READS','API_WRITES','DB_ENTITIES','ADMIN_VISIBILITY','AI_USAGE','PRIVACY','ERROR_STATES','EMPTY_STATES','NATIVE_RISKS','ISSUES','FINAL_STATUS'];
for (const v of mpViews) {
  const name = v.replace(/\.vue$/, '');
  const usage = apiUsage(v, 'apps/mp/src/views');
  const controls = viewControls[v] ?? [];
  const lines = [`# ${name}`, '', `Source: \`apps/mp/src/views/${v}\``, '', `Routes: ${(viewRoutes[name] ?? []).map((p) => `\`${p}\``).join(', ') || '(none)'}`, ''];
  for (const s of SECTIONS) lines.push(`## ${s}`, '', 'TBD', '');
  lines.push('### Static evidence', '');
  lines.push(`- Controls discovered: ${controls.length}`);
  lines.push(`- API reads (static): ${usage.reads.map((x) => `\`${x}\``).join(', ') || '(none)'}`);
  lines.push(`- API writes (static): ${usage.writes.map((x) => `\`${x}\``).join(', ') || '(none)'}`);
  lines.push(`- Candidate fake markers: ${(fakeMarkers.mp[v] ?? []).length}`);
  lines.push('');
  write(`docs/product-audit/pages/mp/${name}.md`, lines.join('\n'));
}
for (const item of adminRoutes.menu) {
  const comp = adminRoutes.routes.find((r) => r.path === item.path)?.component ?? '(none)';
  const controls = adminViewControls[comp] ?? [];
  const lines = [`# admin: ${item.resource} (${item.label})`, '', `Route: \`${item.path}\`  `, `Component: \`apps/admin/src/views/${comp}\``, `Group: ${item.group}`, ''];
  for (const s of SECTIONS) lines.push(`## ${s}`, '', 'TBD', '');
  lines.push('### Static evidence', '');
  lines.push(`- Controls discovered in component: ${controls.length}`);
  lines.push('');
  write(`docs/product-audit/pages/admin/${item.resource}.md`, lines.join('\n'));
}

// ---------- API_DB_ADMIN_MAP.md ----------
const apiMap = ['# API / DB / ADMIN MAP', ''];
apiMap.push(`Total endpoints: ${apiEndpoints.total}`);
apiMap.push('');
apiMap.push('| Method | Path | Controller | Source line |');
apiMap.push('| --- | --- | --- | ---: |');
for (const e of apiEndpoints.endpoints) apiMap.push(`| ${e.method} | \`${e.path}\` | ${e.controller} | ${e.line} |`);
apiMap.push('');
apiMap.push('## DB models');
apiMap.push('');
apiMap.push('| Model |');
apiMap.push('| --- |');
for (const m of dbModels.models) apiMap.push(`| ${m.name} |`);
apiMap.push('');
write('docs/product-audit/API_DB_ADMIN_MAP.md', apiMap.join('\n'));

console.log(JSON.stringify({ mpViews: mpViews.length, adminResources: adminRoutes.menu.length, controls: controlManifest.total }, null, 2));
