<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { api } from '../api';

const items = ref<any[]>([]); const content = ref(''); const deliverAt = ref(''); const saving = ref(false); const error = ref(''); const saved = ref('');
function defaultTime() { const date = new Date(Date.now() + 86_400_000); date.setMinutes(0, 0, 0); deliverAt.value = date.toISOString().slice(0, 16); }
async function load() { try { items.value = (await api.get<any>('/api/v1/future-messages')).items; } catch (cause: any) { error.value = cause?.message ?? '未来信加载失败'; } }
async function save() { if (!content.value.trim() || !deliverAt.value) return; saving.value = true; error.value = ''; try { await api.post('/api/v1/future-messages', { content: content.value, deliverAt: new Date(deliverAt.value).toISOString() }); saved.value = '已保存。到达时间后，系统会通过真实随访队列提醒你。'; content.value = ''; defaultTime(); await load(); } catch (cause: any) { error.value = cause?.message ?? '未来信保存失败'; } finally { saving.value = false; } }
onMounted(() => { defaultTime(); load(); });
</script>
<template><section class="goodnight-page future-page"><header class="simple-header"><button aria-label="返回" @click="$router.back()">‹</button><strong>写给未来的自己</strong><span></span></header><p class="intro">把现在的声音留给未来的你。送达前不会出现在日常列表里。</p><p v-if="error" class="error-note">{{ error }}</p><p v-if="saved" class="success-note">{{ saved }}</p><section class="paper-card"><textarea v-model="content" maxlength="1200" placeholder="此刻你想让未来的自己记住什么？"></textarea><label>送达时间<input v-model="deliverAt" type="datetime-local"></label><button class="primary" :disabled="saving || !content.trim() || !deliverAt" @click="save">{{ saving ? '正在保存...' : '保存这封未来信' }}</button></section><section class="paper-card"><h2>已经写下的信</h2><p v-if="!items.length" class="muted">还没有未来信。</p><article v-for="item in items" :key="item.id" class="letter-row"><p>{{ item.content }}</p><small>{{ item.deliveredAt ? '已经送达' : `计划于 ${new Date(item.deliverAt).toLocaleString('zh-CN')} 送达` }}</small></article></section></section></template>
<style scoped>
.future-page{display:grid;gap:14px;padding:18px 16px 44px;background:#fbf8ef}.simple-header{display:grid;grid-template-columns:40px 1fr 40px;align-items:center;text-align:center;color:var(--gn-green-dark)}.simple-header button{width:36px;height:36px;border:0;border-radius:50%;background:#fff;color:var(--gn-green-dark);font-size:30px;cursor:pointer}.intro,.muted,.error-note,.success-note{color:var(--gn-subtext);line-height:1.7}.error-note{color:var(--gn-danger)}.success-note{margin:0;padding:10px 12px;border-radius:12px;background:var(--gn-green-light);color:var(--gn-green-dark)}.paper-card{display:grid;gap:12px;border:1px solid var(--gn-border);border-radius:24px;background:var(--gn-card);box-shadow:var(--gn-shadow-card);padding:20px}.paper-card textarea{box-sizing:border-box;width:100%;min-height:180px;resize:none;border:1px solid var(--gn-border);border-radius:16px;background:#fffef9;padding:14px;color:var(--gn-text);font:inherit;line-height:1.7}.paper-card label{display:grid;gap:6px;color:var(--gn-green-dark);font-size:13px}.paper-card input{min-height:42px;border:1px solid var(--gn-border);border-radius:12px;padding:8px;font:inherit}.primary{min-height:46px;border:0;border-radius:15px;background:var(--gn-green);color:#fff;font:inherit}.letter-row{padding:12px 0;border-bottom:1px solid var(--gn-border)}.letter-row p{margin:0;color:var(--gn-text);line-height:1.7;white-space:pre-wrap}.letter-row small{display:block;margin-top:6px;color:var(--gn-subtext)}
</style>
