<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { api } from '../api';
const route = useRoute(); const router = useRouter(); const detail = ref<any>(null); const actionTitle = ref(''); const actionDescription = ref(''); const updateContent = ref(''); const busy = ref(false); const error = ref('');
async function load() { const id = String(route.query.id ?? ''); if (!id) { error.value = '缺少旅程编号'; return; } try { detail.value = (await api.get<any>(`/api/v1/journeys/${id}`)).item; } catch (cause: any) { error.value = cause?.message ?? '旅程加载失败'; } }
async function addAction() { if (!actionTitle.value.trim()) return; busy.value = true; try { await api.post(`/api/v1/journeys/${detail.value.journey.id}/actions`, { title: actionTitle.value, description: actionDescription.value }); actionTitle.value = ''; actionDescription.value = ''; await load(); } catch (cause: any) { error.value = cause?.message ?? '行动创建失败'; } finally { busy.value = false; } }
async function addUpdate() { if (!updateContent.value.trim()) return; busy.value = true; try { await api.post(`/api/v1/journeys/${detail.value.journey.id}/updates`, { content: updateContent.value, kind: 'later' }); updateContent.value = ''; await load(); } catch (cause: any) { error.value = cause?.message ?? '进展保存失败'; } finally { busy.value = false; } }
async function confirm() { try { await api.patch(`/api/v1/journeys/${detail.value.journey.id}/situation`, detail.value.snapshot); await load(); } catch (cause: any) { error.value = cause?.message ?? '确认失败'; } }
async function graduate() { busy.value = true; try { await api.post(`/api/v1/journeys/${detail.value.journey.id}/graduate`); await load(); } catch (cause: any) { error.value = cause?.message ?? '暂时还不能结束旅程'; } finally { busy.value = false; } }
onMounted(load);
</script>
<template><section class="page goodnight-page modern-page"><header class="detail-head"><button class="back" @click="router.back()">‹</button><span class="section-kicker">LIFE JOURNEY</span><h1>{{ detail?.journey?.title || '旅程详情' }}</h1><p>{{ detail?.journey?.domain }} · {{ detail?.journey?.stage }}</p></header><p v-if="error" class="error-text">{{ error }}</p><template v-if="detail"><section class="modern-card"><div class="card-heading"><h2>情境快照</h2><span class="stage-badge">{{ detail.snapshot?.confidence === 'agent_draft' ? 'AI 草稿' : '已确认' }}</span></div><div class="snapshot-grid"><div><b>事实</b><span v-for="item in detail.snapshot?.facts" :key="item">{{ item }}</span></div><div><b>感受</b><span v-for="item in detail.snapshot?.feelings" :key="item">{{ item }}</span></div><div><b>需要</b><span v-for="item in detail.snapshot?.needs" :key="item">{{ item }}</span></div><div><b>限制</b><span v-for="item in detail.snapshot?.constraints" :key="item">{{ item }}</span></div></div><button v-if="detail.snapshot?.confidence === 'agent_draft'" class="outline-button full" @click="confirm">这些内容准确</button></section><section class="modern-card"><div class="card-heading"><h2>行动承诺</h2><span>{{ detail.commitments.length }}</span></div><div class="action-form"><input v-model="actionTitle" placeholder="我愿意先做的一件小事" /><input v-model="actionDescription" placeholder="怎样算完成？（可选）" /><button class="primary-button" :disabled="busy" @click="addAction">添加行动</button></div><div v-for="action in detail.commitments" :key="action.id" class="timeline-row"><span :class="['dot', action.status]" /><div><strong>{{ action.title }}</strong><small>{{ action.status === 'completed' ? '已完成' : '等待行动' }}</small></div></div></section><section class="modern-card"><div class="card-heading"><h2>后来呢</h2><span class="section-kicker">真实进展</span></div><textarea v-model="updateContent" maxlength="1000" placeholder="记录事情后来发生了什么，或这一步带来了什么变化" /><button class="outline-button full" :disabled="busy || !updateContent.trim()" @click="addUpdate">保存进展</button></section><section class="modern-card"><h2>时间线</h2><div v-for="update in detail.updates" :key="update.id" class="timeline-row"><span class="dot" /><div><strong>{{ update.kind === 'later' ? '后来呢' : update.kind }}</strong><small>{{ update.content }}</small></div></div><p v-if="!detail.updates.length" class="empty-note">写下第一条进展后，这里会留下真实记录。</p></section><button v-if="detail.journey.status === 'active'" class="graduate-button" :disabled="busy" @click="graduate">完成旅程</button></template></section></template>
<style scoped>
.modern-page{display:grid;gap:16px;padding:0 14px 150px}.detail-head{padding:28px 10px 14px}.back{display:block;margin-bottom:28px;border:0;background:transparent;color:var(--gn-green-dark);font-size:36px;cursor:pointer}.detail-head h1{margin:6px 0;color:var(--gn-green-dark);font-family:var(--gn-font-display);font-size:34px;line-height:1.25}.detail-head p{margin:0;color:var(--gn-subtext)}.modern-card{border:1px solid var(--gn-border);border-radius:var(--gn-radius-card);background:var(--gn-card);box-shadow:var(--gn-shadow-card);padding:22px}.modern-card h2{margin:0;color:var(--gn-text);font-size:21px}.card-heading{display:flex;justify-content:space-between;align-items:center;gap:10px}.stage-badge{padding:6px 10px;border-radius:99px;background:var(--gn-green-light);color:var(--gn-green-dark);font-size:12px}.snapshot-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.snapshot-grid div{display:grid;gap:7px;padding:12px;border-radius:16px;background:#fbfaf3}.snapshot-grid b{color:var(--gn-green-dark);font-size:13px}.snapshot-grid span{color:var(--gn-subtext);font-size:13px;line-height:1.5}.action-form{display:grid;gap:8px;margin-top:18px}.action-form input,.modern-card textarea{border:1px solid var(--gn-border);border-radius:14px;padding:12px;background:#fffdf8;font:inherit}.modern-card textarea{width:100%;box-sizing:border-box;min-height:100px;resize:vertical;line-height:1.6}.primary-button,.outline-button,.graduate-button{border:0;border-radius:15px;padding:12px;background:var(--gn-green);color:#fff;font:inherit;cursor:pointer}.full{width:100%;margin-top:18px;background:transparent;color:var(--gn-green-dark);border:1px solid var(--gn-border)}.timeline-row{display:flex;gap:12px;margin-top:16px}.dot{flex:0 0 10px;width:10px;height:10px;margin-top:6px;border-radius:50%;background:#c7d8b5}.dot.completed{background:var(--gn-green)}.timeline-row strong,.timeline-row small{display:block}.timeline-row small{margin-top:4px;color:var(--gn-subtext);line-height:1.5}.graduate-button{width:100%;background:var(--gn-green-dark)}.empty-note{color:var(--gn-subtext)}.error-text{margin:0 4px;color:var(--gn-danger)}
</style>
