<script setup lang="ts">
import { computed, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { api } from '../api';

const route = useRoute(); const router = useRouter(); const matchId = computed(() => String(route.query.matchId ?? ''));
const feedback = ref('helpful'); const note = ref(''); const busy = ref(false); const error = ref(''); const complete = ref(false);
async function save(shareLater: boolean) { if (!matchId.value) return; busy.value = true; error.value = ''; try { await api.post(`/api/v1/peer-conversations/${encodeURIComponent(matchId.value)}/feedback`, { feedback: feedback.value, note: note.value, shareLater }); complete.value = true; } catch (cause: any) { error.value = cause?.message ?? '这份感受暂时没有保存成功'; } finally { busy.value = false; } }
</script>

<template>
  <section class="goodnight-page peer-graduation-page">
    <header class="graduation-hero"><span>匿名同路</span><h1>这段同行<br>已经走到这里</h1><p>谢谢你们都认真守住了边界。</p></header>
    <article class="graduate-card"><div class="lantern">✦</div><p class="kicker">会话已结束</p><h2>把这一点感受留给自己</h2><p>不需要评价谁，也不需要给出更多解释。你的回答只会用来改善这段同行的安全体验。</p><div class="feelings"><button v-for="option in [{ value: 'helpful', label: '有被接住' }, { value: 'unchanged', label: '没什么变化' }, { value: 'uncomfortable', label: '有点不舒服' }]" :key="option.value" :class="{ selected: feedback === option.value }" @click="feedback = option.value">{{ option.label }}</button></div><label>想留下的一句话（可选）<textarea v-model="note" maxlength="500" placeholder="这里不会成为公开内容，除非你稍后明确同意分享。" /></label><p v-if="complete" class="success-note">已经收好这份感受。谢谢你认真地走完这一段。</p><button class="share" :disabled="busy || complete" @click="save(true)">{{ busy ? '正在保存…' : '以后也想把后来留给同路人' }}</button><button class="later" :disabled="busy || complete" @click="save(false)">{{ complete ? '已完成' : '先把它留给自己' }}</button><button class="back" @click="router.push('/pages/peers/index')">回到同路</button></article><p v-if="error" class="error-note">{{ error }}</p>
  </section>
</template>

<style scoped>
.peer-graduation-page{display:grid;gap:16px;padding:0 16px 54px;background:linear-gradient(180deg,#1c343b 0 268px,#fbf8ef 268px)}.graduation-hero{min-height:246px;padding:32px 12px;color:#f8f1da}.graduation-hero span,.kicker{font-size:12px;letter-spacing:.08em}.graduation-hero h1{margin:32px 0 9px;font-family:var(--gn-font-display);font-size:35px;line-height:1.18}.graduation-hero p{margin:0;color:#d8e2d1;font-size:13px}.graduate-card{display:grid;justify-items:center;gap:14px;margin-top:-48px;border:1px solid var(--gn-border);border-radius:28px;background:#fffdf8;box-shadow:var(--gn-shadow-card);padding:28px 22px;text-align:center}.lantern{display:grid;place-items:center;width:70px;height:70px;border-radius:50%;background:#f5ecd8;color:#9b7b43;font-size:30px}.kicker{margin:0;color:var(--gn-green)}.graduate-card h2{margin:0;color:var(--gn-text);font-size:22px}.graduate-card>p:not(.kicker):not(.success-note){margin:0;color:var(--gn-subtext);line-height:1.72}.feelings{display:flex;flex-wrap:wrap;justify-content:center;gap:8px}.feelings button{min-height:38px;border:1px solid var(--gn-border);border-radius:999px;background:#fffef9;color:var(--gn-subtext);padding:0 12px;font:inherit;cursor:pointer}.feelings button.selected{border-color:var(--gn-green);background:var(--gn-green-light);color:var(--gn-green-dark)}.graduate-card label{display:grid;gap:7px;width:100%;color:var(--gn-text);font-size:13px;text-align:left}.graduate-card textarea{box-sizing:border-box;width:100%;min-height:88px;resize:none;border:1px solid var(--gn-border);border-radius:15px;background:#fffef9;padding:10px;color:var(--gn-text);font:inherit;line-height:1.6}.graduate-card>button{width:100%;min-height:48px;border:0;border-radius:999px;font:inherit;cursor:pointer}.share{background:var(--gn-green);color:#fff}.later{background:#f1f4e9;color:var(--gn-green-dark)}.back{background:transparent;color:var(--gn-subtext)}.success-note{margin:0;color:var(--gn-green);line-height:1.6}.error-note{margin:0;color:var(--gn-danger);text-align:center}
.graduation-hero{position:relative;overflow:hidden}.graduation-hero::after{position:absolute;right:-10px;bottom:-10px;width:228px;height:194px;background:url('../assets/goodnight/peer/peer-night-tree.png') right bottom/contain no-repeat;content:'';opacity:.78;pointer-events:none;-webkit-mask-image:radial-gradient(ellipse at 100% 0%,#000 42%,transparent 88%);mask-image:radial-gradient(ellipse at 100% 0%,#000 42%,transparent 88%)}.graduation-hero>*{position:relative;z-index:1}
</style>
