<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { api } from '../api';

const route = useRoute(); const router = useRouter(); const matchId = computed(() => String(route.query.matchId ?? ''));
const loading = ref(true); const busy = ref(false); const error = ref(''); const match = ref<any>(null);
async function load() { loading.value = true; try { match.value = (await api.get<any>('/api/v1/peer-requests')).items.find((item: any) => item.id === matchId.value) ?? null; } catch (cause: any) { error.value = cause?.message ?? '会话前信息没有加载成功'; } finally { loading.value = false; } }
async function consent() { if (!matchId.value) return; busy.value = true; error.value = ''; try { const response = await api.post<{ conversation: { matchId: string } }>(`/api/v1/peer-matches/${encodeURIComponent(matchId.value)}/consent`, {}); await router.replace(`/pages/peer/conversation?matchId=${encodeURIComponent(response.conversation.matchId)}`); } catch (cause: any) { error.value = cause?.message ?? '暂时无法开启会话'; } finally { busy.value = false; } }
onMounted(load);
</script>

<template>
  <section class="goodnight-page peer-consent-page">
    <header class="consent-hero"><button aria-label="返回请求" @click="router.back()">‹</button><div><span>匿名同路</span><h1>开始前，先确认边界</h1></div></header>
    <p v-if="loading" class="state-note">正在确认这段同行…</p>
    <article v-else class="consent-card"><div class="people"><span class="person-one" aria-hidden="true">⌘</span><i>↔</i><span class="person-two" aria-hidden="true">✦</span></div><h2>你们都没有义务继续</h2><p>你将以匿名身份进入一段限时会话。没有头像、昵称、联系方式或任何可识别信息。</p><ul class="boundary-rules"><li><b>◌</b><span><strong>不展示真实身份</strong><small>彼此匿名，安心倾听。</small></span></li><li><b>◷</b><span><strong>最长 72 小时后结束</strong><small>时间有限，更容易照顾自己。</small></span></li><li><b>⌁</b><span><strong>不交换联系方式</strong><small>专注当下，不带走任何负担。</small></span></li><li><b>◇</b><span><strong>你可以随时结束</strong><small>也可以举报或停止匹配。</small></span></li></ul><p class="draft-note">AI 只能帮你整理草稿，内容不会自动发送。</p><label class="confirm-row"><input type="checkbox" checked disabled><span>我理解并愿意遵守这些匿名边界。</span></label><button :disabled="busy || !match" @click="consent">{{ busy ? '正在开启…' : '同意并开始同行' }}</button><button class="later" :disabled="busy" @click="router.push('/pages/peer/requests')">我想再想想</button></article>
    <p v-if="error" class="error-note">{{ error }}</p>
  </section>
</template>

<style scoped>
.peer-consent-page{display:grid;gap:14px;padding:0 16px 142px;background:linear-gradient(180deg,#213c40 0 182px,#fbf8ef 182px)}.consent-hero{display:grid;grid-template-columns:40px 1fr;align-items:center;gap:10px;min-height:166px;color:#f8f1dc}.consent-hero button{width:36px;height:36px;border:1px solid rgba(255,255,255,.35);border-radius:50%;background:transparent;color:#fff;font-size:28px;line-height:1;cursor:pointer}.consent-hero span{font-size:12px}.consent-hero h1{margin:9px 0 0;font-family:var(--gn-font-display);font-size:28px;line-height:1.22}.consent-card{display:grid;gap:12px;margin-top:-12px;border:1px solid var(--gn-border);border-radius:25px;background:#fffdf7;box-shadow:var(--gn-shadow-card);padding:21px}.people{display:flex;align-items:center;justify-content:center;gap:11px}.people span{display:grid;place-items:center;width:50px;height:50px;border-radius:50%;background:var(--gn-green-light);color:var(--gn-green);font-size:24px}.people i{color:var(--gn-subtext);font-style:normal}.consent-card h2{margin:0;color:var(--gn-text);font-size:20px;text-align:center}.consent-card>p{margin:0;color:var(--gn-subtext);font-size:13px;line-height:1.62;text-align:center}.consent-card ul{display:grid;gap:7px;margin:0;padding:0;list-style:none}.consent-card li{position:relative;padding-left:17px;color:var(--gn-text);font-size:12px;line-height:1.55}.consent-card li::before{position:absolute;left:0;color:var(--gn-green);content:'•'}.confirm-row{display:flex;gap:8px;align-items:start;padding:10px;border-radius:13px;background:#f2f5ea;color:var(--gn-green-dark);font-size:12px;line-height:1.5}.confirm-row input{accent-color:var(--gn-green);margin-top:3px}.consent-card button{min-height:47px;border:0;border-radius:999px;background:var(--gn-green);color:#fff;font:inherit;cursor:pointer}.consent-card .later{min-height:32px;background:transparent;color:var(--gn-subtext)}.state-note,.error-note{margin:0;color:var(--gn-subtext);text-align:center}.error-note{color:var(--gn-danger)}
.consent-hero{position:relative;overflow:hidden}.consent-hero::after{position:absolute;right:0;bottom:0;width:205px;height:145px;background:url('../assets/goodnight/peer/peer-night-hero.png') right bottom/auto 145px no-repeat;content:'';opacity:.93;pointer-events:none;-webkit-mask-image:linear-gradient(90deg,transparent 0%,#000 36%,#000);mask-image:linear-gradient(90deg,transparent 0%,#000 36%,#000)}.consent-hero>*{position:relative;z-index:1}.person-one{background:#edf3e7!important}.person-two{background:#f7eddb!important;color:#a97c48!important}.boundary-rules{display:grid!important;gap:1px!important;margin:0!important;padding:0!important;border:1px solid var(--gn-border);border-radius:16px;overflow:hidden;list-style:none}.boundary-rules li{display:grid!important;grid-template-columns:28px minmax(0,1fr);gap:8px;align-items:center;padding:10px!important;border-bottom:1px solid var(--gn-border)}.boundary-rules li:last-child{border-bottom:0}.boundary-rules li::before{content:none!important}.boundary-rules b{display:grid;place-items:center;width:25px;height:25px;border-radius:50%;background:var(--gn-green-light);color:var(--gn-green);font-size:14px}.boundary-rules span{display:grid;gap:2px}.boundary-rules strong{color:var(--gn-text);font-size:12px}.boundary-rules small{color:var(--gn-subtext);font-size:11px;line-height:1.45}.draft-note{padding:9px 10px;border-radius:12px;background:#f5f1e6;color:var(--gn-green-dark)!important;font-size:11px!important;line-height:1.5!important}
.peer-consent-page{align-content:start}
</style>
