<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { api } from '../api';

const route = useRoute(); const router = useRouter(); const matchId = computed(() => String(route.query.matchId ?? ''));
const feedback = ref('helpful'); const note = ref(''); const busy = ref(false); const error = ref(''); const complete = ref(false);
const conversation = ref<any>(null);
const messageCount = computed(() => conversation.value?.messages?.length ?? 0);
const startedLabel = computed(() => {
  const source = conversation.value?.startsAt;
  return source ? new Date(source).toLocaleDateString('zh-CN', { month: 'numeric', day: 'numeric' }) : '刚刚';
});
async function loadConversation() { try { const response = await api.get<{ items: any[] }>('/api/v1/peer-conversations'); conversation.value = response.items.find((item) => item.matchId === matchId.value) ?? null; } catch { conversation.value = null; } }
async function save(shareLater: boolean) { if (!matchId.value) return; busy.value = true; error.value = ''; try { await api.post(`/api/v1/peer-conversations/${encodeURIComponent(matchId.value)}/feedback`, { feedback: feedback.value, note: note.value, shareLater }); complete.value = true; } catch (cause: any) { error.value = cause?.message ?? '这份感受暂时没有保存成功'; } finally { busy.value = false; } }
onMounted(loadConversation);
</script>

<template>
  <section class="goodnight-page peer-graduation-page">
    <header class="graduation-hero"><span>匿名同路</span><h1>这段同行<br>已经走到这里</h1><p>谢谢你们都认真守住了边界。</p></header>
    <article v-if="conversation" class="journey-summary"><p>这段同行</p><div><span><b>{{ messageCount }}</b><small>条真诚消息</small></span><span><b>72</b><small>小时安全边界</small></span><span><b>{{ startedLabel }}</b><small>开始同行</small></span></div></article>
    <article class="graduate-card"><div class="lantern">✦</div><p class="kicker">会话已结束</p><h2>把这一点感受留给自己</h2><p>不需要评价谁，也不需要给出更多解释。你的回答只会用来改善这段同行的安全体验。</p><div class="feelings"><button v-for="option in [{ value: 'helpful', label: '有被接住' }, { value: 'unchanged', label: '没什么变化' }, { value: 'uncomfortable', label: '有点不舒服' }]" :key="option.value" :class="{ selected: feedback === option.value }" @click="feedback = option.value">{{ option.label }}</button></div><label>想留下的一句话（可选）<textarea v-model="note" maxlength="500" placeholder="这里不会成为公开内容，除非你稍后明确同意分享。" /></label><p v-if="complete" class="success-note">已经收好这份感受。谢谢你认真地走完这一段。</p><button class="share" :disabled="busy || complete" @click="save(true)">{{ busy ? '正在保存…' : '以后也想把后来留给同路人' }}</button><button class="later" :disabled="busy || complete" @click="save(false)">{{ complete ? '已完成' : '先把它留给自己' }}</button><button class="back" @click="router.push('/pages/peers/index')">回到同路</button></article><p v-if="error" class="error-note">{{ error }}</p>
  </section>
</template>

<style scoped>
.peer-graduation-page{display:grid;gap:14px;padding:0 16px 54px;background:linear-gradient(180deg,#1c343b 0 244px,#fbf8ef 244px)}.graduation-hero{min-height:224px;padding:27px 12px;color:#f8f1da}.graduation-hero span,.kicker{font-size:12px;letter-spacing:.08em}.graduation-hero h1{max-width:275px;margin:25px 0 8px;font-family:var(--gn-font-display);font-size:32px;line-height:1.16}.graduation-hero p{max-width:250px;margin:0;color:#d8e2d1;font-size:13px}.graduate-card{display:grid;justify-items:center;gap:12px;margin-top:-43px;border:1px solid var(--gn-border);border-radius:25px;background:#fffdf8;box-shadow:var(--gn-shadow-card);padding:23px 20px;text-align:center}.lantern{display:grid;place-items:center;width:62px;height:62px;border-radius:50%;background:#f5ecd8;color:#9b7b43;font-size:27px}.kicker{margin:0;color:var(--gn-green)}.graduate-card h2{margin:0;color:var(--gn-text);font-size:21px}.graduate-card>p:not(.kicker):not(.success-note){margin:0;color:var(--gn-subtext);font-size:13px;line-height:1.65}.feelings{display:flex;flex-wrap:wrap;justify-content:center;gap:7px}.feelings button{min-height:36px;border:1px solid var(--gn-border);border-radius:999px;background:#fffef9;color:var(--gn-subtext);padding:0 11px;font:inherit;font-size:13px;cursor:pointer}.feelings button.selected{border-color:var(--gn-green);background:var(--gn-green-light);color:var(--gn-green-dark)}.graduate-card label{display:grid;gap:6px;width:100%;color:var(--gn-text);font-size:13px;text-align:left}.graduate-card textarea{box-sizing:border-box;width:100%;min-height:80px;resize:none;border:1px solid var(--gn-border);border-radius:14px;background:#fffef9;padding:10px;color:var(--gn-text);font:inherit;line-height:1.55}.graduate-card>button{width:100%;min-height:46px;border:0;border-radius:999px;font:inherit;cursor:pointer}.share{background:var(--gn-green);color:#fff}.later{background:#f1f4e9;color:var(--gn-green-dark)}.back{background:transparent;color:var(--gn-subtext)}.success-note{margin:0;color:var(--gn-green);line-height:1.6}.error-note{margin:0;color:var(--gn-danger);text-align:center}
.graduation-hero{position:relative;overflow:hidden}.graduation-hero::after{position:absolute;right:0;bottom:0;width:222px;height:160px;background:url('../assets/goodnight/peer/peer-night-hero.png') right bottom/auto 160px no-repeat;content:'';opacity:.93;pointer-events:none;-webkit-mask-image:linear-gradient(90deg,transparent 0%,#000 36%,#000);mask-image:linear-gradient(90deg,transparent 0%,#000 36%,#000)}.graduation-hero>*{position:relative;z-index:1}.journey-summary{display:grid;gap:11px;margin-top:-34px;border:1px solid var(--gn-border);border-radius:22px;background:rgba(255,253,248,.95);box-shadow:var(--gn-shadow-card);padding:16px}.journey-summary + .graduate-card{margin-top:0}.journey-summary>p{margin:0;color:var(--gn-green-dark);font-size:16px;font-weight:700}.journey-summary>div{display:grid;grid-template-columns:repeat(3,1fr)}.journey-summary span{display:grid;justify-items:center;gap:4px;padding:0 5px;border-right:1px solid var(--gn-border)}.journey-summary span:last-child{border-right:0}.journey-summary b{color:var(--gn-green-dark);font-family:var(--gn-font-display);font-size:22px}.journey-summary small{color:var(--gn-subtext);font-size:11px;text-align:center;line-height:1.35}
.peer-graduation-page{align-content:start;padding-bottom:142px}
</style>
