<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { api } from '../api';

const items = ref<any[]>([]); const contacts = ref<any[]>([]); const form = ref({ recipient: '', channel: '当面聊', summary: '' }); const contact = ref({ nickname: '', relation: '', contactHint: '' }); const error = ref(''); const saving = ref(false);
async function load() { try { const [handoffs, trusted] = await Promise.all([api.get<any>('/api/v1/handoffs'), api.get<any>('/api/v1/trusted-contacts')]); items.value = handoffs.items; contacts.value = trusted.items; } catch (cause: any) { error.value = cause?.message ?? '现实支持资料加载失败'; } }
async function saveContact() { if (!contact.value.nickname.trim() || !contact.value.contactHint.trim()) return; saving.value = true; try { await api.post('/api/v1/trusted-contacts', contact.value); contact.value = { nickname: '', relation: '', contactHint: '' }; await load(); } catch (cause: any) { error.value = cause?.message ?? '联系人保存失败'; } finally { saving.value = false; } }
async function createHandoff() { if (!form.value.recipient.trim() || !form.value.summary.trim()) return; saving.value = true; try { await api.post('/api/v1/handoffs', form.value); form.value = { recipient: '', channel: '当面聊', summary: '' }; await load(); } catch (cause: any) { error.value = cause?.message ?? '交接内容保存失败'; } finally { saving.value = false; } }
async function share(id: string) { saving.value = true; try { await api.post(`/api/v1/handoffs/${encodeURIComponent(id)}/share`, {}); await load(); } catch (cause: any) { error.value = cause?.message ?? '交接状态更新失败'; } finally { saving.value = false; } }
onMounted(load);
</script>
<template>
  <section class="goodnight-page handoff-page"><header class="simple-header"><span>把一部分交给现实</span><strong>现实支持</strong><span></span></header><p class="intro">这里保存的是你亲自确认过的支持安排。系统不会替你联系任何人。</p><p v-if="error" class="error-note">{{ error }}</p><section class="paper-card"><h2>新增现实交接</h2><label>交接给谁<input v-model="form.recipient" maxlength="80" placeholder="例如：小林 / 我的咨询师"></label><label>怎么联系<select v-model="form.channel"><option>当面聊</option><option>电话</option><option>消息</option><option>其他</option></select></label><label>想让对方知道什么<textarea v-model="form.summary" maxlength="1000" placeholder="写清楚你希望对方知道的事实与需要的帮助"></textarea></label><button class="primary" :disabled="saving || !form.recipient.trim() || !form.summary.trim()" @click="createHandoff">保存交接</button></section><section class="paper-card"><h2>已保存的交接</h2><p v-if="!items.length" class="muted">还没有交接安排。</p><article v-for="item in items" :key="item.id" class="saved-row"><div><strong>{{ item.recipient }}</strong><span>{{ item.channel }} · {{ item.status === 'shared' ? '已标记为已分享' : '仅自己可见' }}</span><p>{{ item.summary }}</p></div><button v-if="item.status !== 'shared'" class="outline" :disabled="saving" @click="share(item.id)">标记已分享</button></article></section><section class="paper-card"><h2>支持联系人</h2><article v-for="person in contacts" :key="person.id" class="contact-row"><strong>{{ person.nickname }}</strong><span>{{ person.relation || '联系人' }} · {{ person.contactHint }}</span></article><div class="contact-form"><input v-model="contact.nickname" placeholder="称呼"><input v-model="contact.relation" placeholder="关系"><input v-model="contact.contactHint" placeholder="联系方式提示"><button class="outline" :disabled="saving" @click="saveContact">保存联系人</button></div></section></section>
</template>
<style scoped>
.handoff-page{display:grid;gap:14px;padding:18px 16px 44px;background:#fbf8ef}.simple-header{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;color:var(--gn-green-dark);text-align:center}.simple-header span:first-child{text-align:left;color:var(--gn-subtext);font-size:12px}.simple-header span:last-child{min-height:1px}.intro,.muted,.error-note{color:var(--gn-subtext);line-height:1.7}.paper-card{display:grid;gap:12px;border:1px solid var(--gn-border);border-radius:24px;background:var(--gn-card);box-shadow:var(--gn-shadow-card);padding:20px}.paper-card h2{margin:0;color:var(--gn-text);font-size:19px}.paper-card label{display:grid;gap:6px;color:var(--gn-green-dark);font-size:13px}.paper-card input,.paper-card select,.paper-card textarea,.contact-form input{box-sizing:border-box;width:100%;min-height:42px;border:1px solid var(--gn-border);border-radius:12px;background:#fffef9;padding:9px 11px;color:var(--gn-text);font:inherit}.paper-card textarea{min-height:108px;resize:none}.primary,.outline{min-height:44px;border-radius:14px;padding:0 15px;font:inherit;cursor:pointer}.primary{border:0;background:var(--gn-green);color:#fff}.outline{border:1px solid var(--gn-border);background:#fffef9;color:var(--gn-green-dark)}button:disabled{opacity:.55;cursor:default}.saved-row,.contact-row{display:flex;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid var(--gn-border)}.saved-row strong,.saved-row span,.contact-row strong,.contact-row span{display:block}.saved-row span,.contact-row span{margin-top:4px;color:var(--gn-subtext);font-size:12px}.saved-row p{margin:8px 0 0;color:var(--gn-text);line-height:1.6}.contact-form{display:grid;grid-template-columns:1fr 1fr;gap:8px}.contact-form input:last-of-type{grid-column:1/-1}.contact-form button{grid-column:1/-1}
</style>
