<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { api } from '../api';

const fields = [{ key: 'food', label: '吃过东西' }, { key: 'outside', label: '出门或见到阳光' }, { key: 'humanContact', label: '和可信任的人有联系' }, { key: 'sleep', label: '睡眠有被照顾' }, { key: 'mustDo', label: '完成一件必须做的事' }, { key: 'comfort', label: '做了一件让自己舒服的事' }];
const signals = ref<Record<string, string>>(Object.fromEntries(fields.map((field) => [field.key, 'partial']))); const items = ref<any[]>([]); const summary = ref(''); const saving = ref(false); const error = ref('');
async function load() { try { items.value = (await api.get<any>('/api/v1/me/recovery')).items; } catch (cause: any) { error.value = cause?.message ?? '恢复记录加载失败'; } }
async function save() { saving.value = true; try { await api.post('/api/v1/me/recovery', { signals: signals.value, summary: summary.value }); summary.value = ''; await load(); } catch (cause: any) { error.value = cause?.message ?? '恢复记录保存失败'; } finally { saving.value = false; } }
onMounted(load);
</script>
<template><section class="goodnight-page recovery-page"><header class="simple-header"><button aria-label="返回" @click="$router.back()">‹</button><strong>记录恢复情况</strong><span></span></header><p class="intro">这里关注生活功能的变化，不给你贴标签，也不替代专业帮助。</p><p v-if="error" class="error-note">{{ error }}</p><section class="paper-card"><h2>今天的我</h2><article v-for="field in fields" :key="field.key" class="signal-row"><strong>{{ field.label }}</strong><div><button v-for="option in [{ value: 'yes', label: '做到了' }, { value: 'partial', label: '一部分' }, { value: 'no', label: '还没有' }]" :key="option.value" :class="{ active: signals[field.key] === option.value }" @click="signals[field.key] = option.value">{{ option.label }}</button></div></article><textarea v-model="summary" maxlength="500" placeholder="今天有什么值得被看见的小变化？"></textarea><button class="primary" :disabled="saving" @click="save">{{ saving ? '正在记录...' : '保存今天的记录' }}</button></section><section class="paper-card"><h2>之前的记录</h2><p v-if="!items.length" class="muted">还没有恢复记录。</p><article v-for="item in items" :key="item.id" class="history-row"><time>{{ new Date(item.createdAt).toLocaleString('zh-CN') }}</time><p>{{ item.summary }}</p></article></section></section></template>
<style scoped>
.recovery-page{display:grid;gap:14px;padding:18px 16px 44px;background:#fbf8ef}.simple-header{display:grid;grid-template-columns:40px 1fr 40px;align-items:center;text-align:center;color:var(--gn-green-dark)}.simple-header button{width:36px;height:36px;border:0;border-radius:50%;background:#fff;color:var(--gn-green-dark);font-size:30px;cursor:pointer}.intro,.muted,.error-note{color:var(--gn-subtext);line-height:1.7}.error-note{color:var(--gn-danger)}.paper-card{display:grid;gap:12px;border:1px solid var(--gn-border);border-radius:24px;background:var(--gn-card);box-shadow:var(--gn-shadow-card);padding:20px}.paper-card h2{margin:0;color:var(--gn-text);font-size:19px}.signal-row{display:grid;gap:8px;padding:10px 0;border-bottom:1px solid var(--gn-border)}.signal-row strong{color:var(--gn-text);font-size:14px}.signal-row div{display:flex;gap:8px;flex-wrap:wrap}.signal-row button{border:1px solid var(--gn-border);border-radius:999px;background:#fffef9;padding:7px 12px;color:var(--gn-subtext);font:inherit}.signal-row button.active{border-color:var(--gn-green);background:var(--gn-green);color:#fff}.paper-card textarea{box-sizing:border-box;width:100%;min-height:88px;resize:none;border:1px solid var(--gn-border);border-radius:14px;padding:10px;font:inherit}.primary{min-height:46px;border:0;border-radius:15px;background:var(--gn-green);color:#fff;font:inherit}.history-row{border-bottom:1px solid var(--gn-border);padding:9px 0}.history-row time{color:var(--gn-subtext);font-size:12px}.history-row p{margin:5px 0 0;color:var(--gn-text);line-height:1.6}
</style>
