# Runs every Goodnight TreeHole backup: code, database, and a MinIO note.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts/backup-all.ps1
#   powershell -ExecutionPolicy Bypass -File scripts/backup-all.ps1 -BackupRoot E:\Backups
#
# Exits non-zero if any component failed. The .env file is deliberately NOT copied by
# this script: it holds secrets, and docs/private-env-backup-guide.md explains where the
# owner should keep it instead.

param(
  [string]$BackupRoot
)

$ErrorActionPreference = 'Continue'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$stamp = Get-Date -Format 'yyyyMMdd-HHmm'
$results = [ordered]@{}

# Resolved once, up front, because every step writes under it. D: is the documented
# location but it is a removable volume on this machine and is not always mounted.
$root = if ($BackupRoot) { $BackupRoot } elseif (Test-Path 'D:\') { 'D:\Backups' } else { Join-Path $env:USERPROFILE 'Backups' }
New-Item -ItemType Directory -Force -Path $root | Out-Null

function Invoke-Step([string]$Name, [scriptblock]$Action) {
  Write-Host ''
  Write-Host "################ $Name ################"
  try {
    & $Action
    $code = $LASTEXITCODE
  } catch {
    Write-Host "exception: $_"
    $code = 1
  }
  if ($null -eq $code) { $code = 0 }
  $results[$Name] = $code
  Write-Host "$Name exit code: $code"
}

Invoke-Step 'backup-code' {
  & powershell -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'backup-code.ps1') @(
    if ($BackupRoot) { '-BackupRoot', $BackupRoot }
  )
}

Invoke-Step 'backup-db' {
  & powershell -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'backup-db.ps1') @(
    if ($BackupRoot) { '-BackupRoot', $BackupRoot }
  )
}

Write-Host ''
Write-Host '################ minio ################'
# MinIO is declared in docker-compose.yml but the API never uses it: uploads are written
# to a local directory (resolveUploadsDirectory in apps/api/src/runtime-environment.ts),
# and no MINIO_* variable is read anywhere in the API source. There is therefore no
# application object store to back up. The check below only records whether the service
# is running, so a future change that starts using it is noticed.
$minioRunning = $false
try {
  $connection = Get-NetTCPConnection -LocalPort 19000 -State Listen -ErrorAction SilentlyContinue
  $minioRunning = [bool]$connection
} catch { }
Write-Host "minio reachable on 19000: $minioRunning"
Write-Host 'no application objects are stored in MinIO; see docs/disaster-recovery-inventory.md section 4'
$results['minio'] = 0

Write-Host ''
Write-Host '################ recovery evidence ################'
# artifacts/ is gitignored, so the screenshots and manifests the recovery documents cite
# are not in the repository and not in the code bundle. Most of artifacts/ can be
# regenerated by re-running its scripts, but the emulator session evidence cannot be
# reproduced without the device, so it is archived here.
#
# Service logs are excluded on purpose: start-services.ps1 redirects the running dev
# servers' stdout/stderr into this directory, so those files are held open and are runtime
# output rather than evidence. A staging copy is used so a single unreadable file cannot
# abort the archive.
$evidenceSource = Join-Path $repoRoot 'artifacts\recovery'
$evidenceCode = 0
if (Test-Path $evidenceSource) {
  $evidenceDir = Join-Path $root 'goodnight-treehole-recovery-evidence'
  New-Item -ItemType Directory -Force -Path $evidenceDir | Out-Null
  $evidenceZip = Join-Path $evidenceDir "recovery-evidence-$stamp.zip"
  $staging = Join-Path ([System.IO.Path]::GetTempPath()) "gn-evidence-$stamp"
  try {
    New-Item -ItemType Directory -Force -Path $staging | Out-Null
    $copied = 0
    $skipped = @()
    foreach ($file in Get-ChildItem -Path $evidenceSource -Recurse -File) {
      if ($file.Extension -eq '.log') { continue }
      try {
        Copy-Item -Path $file.FullName -Destination (Join-Path $staging $file.Name) -Force -ErrorAction Stop
        $copied++
      } catch {
        $skipped += $file.Name
      }
    }
    if ($skipped.Count) { Write-Host "WARNING: could not read $($skipped.Count) file(s): $($skipped -join ', ')" }
    if ($copied -eq 0) { throw 'no readable evidence files to archive' }
    Compress-Archive -Path (Join-Path $staging '*') -DestinationPath $evidenceZip -Force
    $evidenceBytes = (Get-Item $evidenceZip).Length
    Write-Host "evidence archive: $evidenceZip ($evidenceBytes bytes, $copied files)"
    if ($evidenceBytes -le 0) { Write-Host 'ERROR: evidence archive is empty'; $evidenceCode = 1 }
  } catch {
    Write-Host "exception archiving evidence: $_"
    $evidenceCode = 1
  } finally {
    if (Test-Path $staging) { Remove-Item -Recurse -Force $staging -ErrorAction SilentlyContinue }
  }
} else {
  Write-Host "no artifacts/recovery directory to archive"
}
$results['evidence'] = $evidenceCode

Write-Host ''
Write-Host '################ summary ################'
$failed = @()
foreach ($key in $results.Keys) {
  $status = if ($results[$key] -eq 0) { 'PASS' } else { 'FAIL' }
  Write-Host ("{0,-14} {1}" -f $key, $status)
  if ($results[$key] -ne 0) { $failed += $key }
}

$summaryPath = Join-Path $root "backup-all-$stamp.json"
([ordered]@{
  timestamp = (Get-Date).ToString('o')
  repo      = $repoRoot
  backupRoot = $root
  results   = $results
  failed    = $failed
  ok        = ($failed.Count -eq 0)
}) | ConvertTo-Json -Depth 4 | Set-Content -Path $summaryPath -Encoding UTF8
Write-Host "summary: $summaryPath"

if ($failed.Count -gt 0) {
  Write-Host "`n=== backup-all FAILED: $($failed -join ', ') ==="
  exit 1
}
Write-Host "`n=== backup-all PASS ==="
exit 0
